### ISSUE TITLE
Cannot support obs-websocket 5.1.0 Protocol

### ISSUE THREAD

**Issue by coco-hkk** [miaulightouch/obs-virtual-cam#11]
- win11 x64
- obs 30.1.2 portable
- python 3.12.2
- obs-websocket 5.1.0

I wanna open more than one virtual camera using obs-websocket, eg:

```python
from obswebsocket import obsws, requests

...

virtual_cam_status = self.client.call(requests.GetVirtualCamStatus())
if virtual_cam_status.datain["outputActive"] is False:
    self.client.call(requests.StartVirtualCam())
    time.sleep(1)

...
```

there is an error:
```
if virtual_cam_status.datain["outputActive"] is False:
       ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'outputActive'
```

Portable version does not support obs-websocket after installing obs-virtualcam.
However, the full install version works fine without obs-virtualcam.

https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getvirtualcamstatus

**Comment by miaulightouch** [comment]
All virtual camera-related commands are for OBS's built-in virtual camera. The portable version of OBS may not register the virtual camera in Windows, which could cause this issue.

I have nothing that could help; this plugin does not support obs-websocket.

It's off-topic at this repository. Please report to the official OBS repository.
