### ISSUE TITLE
Release 2.1.0 has version 2.0.12 files attached but seem to contain 2.1.0!?

### ISSUE THREAD

**Issue by rse** [miaulightouch/obs-virtual-cam#23]
The version 2.1.0 exists under "releases", but the attached asset has the filename "obs-virtualcam-2.0.12-windows-x64-Installer.exe", although the timestamps of the contained files indicate that this is version 2.1.0. Can you fix this and upload the final 2.1.0 version to avoid version confusion? Thanks.

**Comment by miaulightouch** [comment]
Sorry, it should be fixed now. I'm very sorry for the inconvenience.

**Comment by rse** [comment]
Many thanks!
